version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: petsdb
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: petpass
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"

volumes:
  db_data:
